### GET '/'
GET http://localhost:5050

### POST '/auth/register
POST http://localhost:5050/auth/register
Content-Type: application/json

{
    "username": "Putin",
    "password": "I_want_to_bomb_Ukraine"
}

### login
POST http://localhost:5050/auth/login
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc3NzM0OTAwfQ.sOQaHRps-11ubupLPVyVOOdHdC3Y3HAKpBKLecSu1h8

{
    "username": "Putin",
    "password": "I_want_to_bomb_Ukraine"
}

### getExercises
GET http://localhost:5050/exercises
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc3NzM0OTI4fQ.x3myFfcDqAB6cu8LlV2Z5IuR_4Vkmal_u1hcun73e1g

### create exercise
POST http://localhost:5050/exercises/create_exercise
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc3NzM0OTAwfQ.sOQaHRps-11ubupLPVyVOOdHdC3Y3HAKpBKLecSu1h8

{
    "title": "6:8 time practice",
    "type": "strumming pattern",
    "duration": "2"
}

### complete exercise
POST http://localhost:5050/exercises/update_exercise/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc3NzM0OTI4fQ.x3myFfcDqAB6cu8LlV2Z5IuR_4Vkmal_u1hcun73e1g